version: '3.5'

services:

  #nome do servico
  blog-django:

    #construido a partir de uma imagem customizada em ./image
    image: blog-django
    
    #nome do conteiner
    container_name: blog-django

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/root"

    #porta a ser exposta
    ports:
      - 8080:8080
  
    #artifício para manter o container aberto
    tty: true
